'use-client';

import './globals.css'
import { Inter } from 'next/font/google'
import {getServerSession} from 'next-auth'
import Link from 'next/link'
import Logout from './logout'
const inter = Inter({ subsets: ['latin'] })

import Providers from "./components/provider"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <nav className = "bg-white border-2 text-black from-stone-700 to-green-600">
          {!!session && 
            <Logout/>
          }
          {!!session && 
            <Link className = "px-10" href = "/dashboard">
            DASHBOARD
            </Link>
          }
          {
            !session &&
            
            <Link className = "px-10" href = "/login">
              Login
              </Link>
              
          }
           {
            !session &&
            
            <Link className = "px-10" href = "/register">
              REGISTER
              </Link>
              
          }
          </nav>
        {children}
        </Providers>
    </body>
    </html>
  );
}
